### ISSUE TITLE
Error: Cannot find module '/home/astroberry/mobindi/dist/app.js'

### ISSUE THREAD

**Issue by franky384** [pludov/mobindi#14]
Seems not to build correct, i get a lot of errors and warnings.
There is no mobindi/dist folder at all.
Tried on Raspberry pi 3 with astroberry-server image (ubuntu16.04) an on my laptop with ubuntu 18.04 x64
[mobindi.txt](https://github.com/pludov/mobindi/files/3227749/mobindi.txt)

I attach the complete console output of the build process.
Please help

**Comment by pludov** [comment]
hello

you must issue "npm run-script build" from ~/mobindi

**Comment by pludov** [comment]
This was indeed missing from the doc. Fixed.
