### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by maaudrana** [pludov/mobindi#3]
hi @pludov 
their is no doubt that it is an awsome project but the project does not have any logo.As a designer i want to provide a design for this project,I just need a permission so that my work does not go in vain.its free for open source projct
thanks

**Comment by pludov** [comment]
Hi!
Thank you for your interest ! I am very open to contribution !

Pludov

**Comment by pludov** [comment]
@maaudrana : hi! still working on this ?

**Comment by maaudrana** [comment]
Actually  my computer was broken suddenly .can not working  on it.sorry
