### ISSUE TITLE
astroberry pi, port 8080

### ISSUE THREAD

**Issue by chboing** [pludov/mobindi#54]
Hello,
Not sur if real problem or not since it's in a **"Next release" paragraph**, but I have trouble launching mobindi in astroberry

How i launch :
```
astroberry@astroberry:~/mobindi $ cat mobindi.conf 
LOGDIR='/var/log/mobindi'
PORT=8081
astroberry@astroberry:~/mobindi $ ./install.sh 
Settings:
 * Log directory: /var/log/mobindi
System ready
astroberry@astroberry:~/mobindi $ ./startup.sh 
Nginx reloaded
 
> mobindi-backend@1.1.0 start
> node dist/app.js
 
astroberry@astroberry:~/mobindi $ 
```

Logs
```
2021-07-03T09:43:01.087Z info  [Log.js] Starting
2021-07-03T09:43:01.608Z error [app.js] Got express error listen EADDRINUSE: address already in use :::8080 Error: listen EADDRINUSE: address already in use :::8080
    at Server.setupListenHandle [as _listen2] (node:net:1305:16)
    at listenInCluster (node:net:1353:12)
    at Server.listen (node:net:1440:7)
    at init (/home/astroberry/mobindi/app.ts:274:12)
    at Immediate.<anonymous> (/home/astroberry/mobindi/app.ts:319:9)
    at processImmediate (node:internal/timers:464:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '::',
  port: 8080
}
2021-07-03T09:43:01.709Z info  [Log.js] Process terminating with code 0
```

I've had some more success with exporting, then install, then launch instead of using mobindi.con
`export PORT=8082`

I can then acces UI, and even take pictures, but then won't come back to UI
[>>capture<<](https://imgur.com/tCzFmna)

;)

**Comment by chboing** [comment]
The picture won't come back to UI because chrome is doing this:

`Mixed Content: The page at 'https://192.168.1.112:8443/' was loaded over HTTPS, but requested an insecure element 'http://192.168.1.112:8081/fitsviewer/fitsviewer.cgi?bin=2&path=%2Fhome%2Fastroberry%2FIMAGE_008.fits&low=0.05&med=0.5&high=0.95'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html`

if i hit the fitsviewer directly in http i get the image back ...

**Comment by pludov** [comment]
Hi !
Glad it is still working with firefox ! Mixed content was per design, to avoid costly https encryption on low end hardware like RPI. It will certainly need to be changed at least for chrome.

For the port issue, there is probably something else running on port 8080 under astroberry... 8080 is a often choose port number

**Comment by chboing** [comment]
Yes, but the issue is I put PORT=8081 in mobindi.conf -> it's still trying to launch on 8080

**Comment by pludov** [comment]
master version will now always stay on https when chrome is detected (no more mixed content).
Also handling of non default port setting was just fixed
