### ISSUE TITLE
not starting with ubuntu 20.04

### ISSUE THREAD

**Issue by pludov** [pludov/mobindi#62]
Hello.

I switched to 20.04LTS for the nafabox, on the other hand I can no longer launch Mobindi at startup.

Each time you restart, the service that starts mobindi does not start. I have to start startup.sh by hand. Then CTRL + C. Then there the service wants this launch. 

The service : 

`[Unit]
Description=MobIndi
After=multi-user.target

[Service]
Type=idle
User=nafabox
ExecStart=/home/nafabox/bin/mobindi/startup.sh
Restart=Always
RestartSec=5
[Install]
WantedBy=multi-user.target`

Error message : 

`Started MobIndi.
mobindi.service: Main process exited, code=exited, status=1/FAILURE
mobindi.service: Failed with result 'exit-code'
/etc/systemd/system/mobindi.service:9: Failed to parse service restart specifier, ignoring: Always
`

_Originally posted by @dragonlost in https://github.com/pludov/mobindi/issues/31#issuecomment-977264859_

**Comment by dragonlost** [comment]
thx for futur help !

**Comment by pludov** [comment]
Hi dragonlost, your specific error seems related to case sensitivity (use always instead of Always)

I added some doc in the README.md for this anyway
